# Default values for cloudcasa-register.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# AMDS_CLUSTER_ID: 5fc0d782192031391f205b5f

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
